### ISSUE TITLE
how to install this tool kit

### ISSUE THREAD

**Issue by safaldas** [linuxdeepin/deepin-tool-kit#11]
I was trying to build deepin from source in debian 9 
`Package dtkbase-0-2 not found`
This is the error i get cant seem to find this package any where how to install this?
Thanks

**Comment by Iceyer** [comment]
Where you get the source code, it seems too old...
Just build this two repository , get fetch you code to the newest.

https://github.com/linuxdeepin/dtkcore
https://github.com/linuxdeepin/dtkwidget

Then you can get package like libdtkcore2/libdtkwidget2, all deepin apps depends this package now.




But if you want to build dtkbase-0-2, you can get source from branch dtk-0.2:

https://github.com/linuxdeepin/deepin-tool-kit/tree/dtk-0.2

However, we do not maintainer this branch now!!!

**Comment by aiamuzz** [comment]
wouldn't it be good idea to have a page similar to the one found on '[debian wiki](https://wiki.debian.org/BuildingTutorial)' ??? ... a complete noob guide to setup an environment for build/development.

I tried looking for something like that on deepin wiki ... but couldn't find it.

**Comment by hosiet** [comment]
As a joint effort between Debian and Deepin, we are preparing `deepin-tool-kit` inside Debian Testing/Unstable.

* dtkcore: https://tracker.debian.org/pkg/dtkcore
* dtkwm: https://tracker.debian.org/pkg/dtkwm
* dtkwidget: https://tracker.debian.org/pkg/dtkwidget

You will be able to build those libraries using standard methods for debian packages.

The work is not finished (yet). We expect this work done by Spring 2018.

**Comment by AnwarShah** [comment]
Waiting for this to finish. It's hard to guess how i can build deepin environment from all the repos. You should consider archiving these

**Comment by hosiet** [comment]
Not quite sure what your need is. Libdtk is only a small part of the entire libraries Deepin is using; you might encounter extra build dependencies if you want to build one specific Deepin application.

If you need a (rather) complete dependency graph, see https://salsa.debian.org/pkg-deepin-team/progress-tracker/blob/master/depgraph/pkg-deepin-dep.svg .

**Comment by albe-rosado** [comment]
@hosiet 哪里可以看DTK的说明书？官网链接站来到这个repo，但是README.md啥都没有。 非常感谢你们

**Comment by hosiet** [comment]
Please consider looking into the subrepos directly.

@Iceyer a README should be added.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
