### ISSUE TITLE
error while trying to compile with mingw

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-tool-kit#14]
When I try to compile it with mingw in Archlinux, I get this error,

> release/dutiltester.o:dutiltester.cpp:(.text+0x182): undefined reference to `__imp__ZN3Dtk4Core8DPathBufC1ERK7QString'

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
