### ISSUE TITLE
KDENLIVE crashes with dlight theme

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-tool-kit#16]
If we change the theme with qt5ct and set qt theme to dlight, then programs such as kdenlive crashes.
Here is the backtrace,

> Application: Kdenlive (kdenlive), signal: Segmentation fault
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> [Current thread is 1 (Thread 0x7f6bfc976d80 (LWP 2342))]
> 
> Thread 13 (Thread 0x7f6bfa91f700 (LWP 2361)):
>  0x00007f6c0801ad16 in ppoll () at /usr/lib/libc.so.6
>  0x00007f6c02c3fa13 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
>  0x00007f6c02c3ffe0 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
>  0x00007f6bde477847 in  () at /usr/lib/libSDL2-2.0.so.0
>  0x00007f6bde3cf046 in  () at /usr/lib/libSDL2-2.0.so.0
>  0x00007f6bde415f9f in  () at /usr/lib/libSDL2-2.0.so.0
>  0x00007f6bde4996ea in  () at /usr/lib/libSDL2-2.0.so.0
>  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
>  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 12 (Thread 0x7f6bb6664700 (LWP 2360)):
>  0x00007f6c0801ac21 in poll () at /usr/lib/libc.so.6
>  0x00007f6c02ef8ee0 in  () at /usr/lib/libglib-2.0.so.0
>  0x00007f6c02ef8fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
>  0x00007f6c086c6fe4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
>  0x00007f6c086728cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
>  0x00007f6c084bbeb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
>  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
>  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
>  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 11 (Thread 0x7f6bb6e65700 (LWP 2359)):
> #0  0x00007f6c0742dafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
> #1  0x00007f6c0acf16e4 in  () at /usr/lib/libmlt.so.6
> #2  0x0000560a3650bfbe in  ()
> #3  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
> #4  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #5  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 10 (Thread 0x7f6bb7666700 (LWP 2358)):
> #0  0x00007f6c080167a4 in read () at /usr/lib/libc.so.6
> #1  0x00007f6c02ea7781 in  () at /usr/lib/libglib-2.0.so.0
> #2  0x00007f6c02ef7a50 in g_main_context_check () at /usr/lib/libglib-2.0.so.0
> #3  0x00007f6c02ef8e86 in  () at /usr/lib/libglib-2.0.so.0
> #4  0x00007f6c02ef8fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
> #5  0x00007f6c086c6fe4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #6  0x00007f6c086728cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #7  0x00007f6c084bbeb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
> #8  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
> #9  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #10 0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 9 (Thread 0x7f6baffff700 (LWP 2357)):
> #0  0x00007f6c0742dafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
> #1  0x00007f6bda3d7c96 in  () at /usr/lib/mlt/libmltsdl2.so
> #2  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #3  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 8 (Thread 0x7f6bd426c700 (LWP 2356)):
> #0  0x00007f6c080167a4 in read () at /usr/lib/libc.so.6
> #1  0x00007f6bfeb8c782 in pa_read () at /usr/lib/pulseaudio/libpulsecommon-12.2.so
> #2  0x00007f6c02c3f55f in pa_mainloop_prepare () at /usr/lib/libpulse.so.0
> #3  0x00007f6c02c3ffd1 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
> #4  0x00007f6c02c40091 in pa_mainloop_run () at /usr/lib/libpulse.so.0
> #5  0x00007f6bde4779b0 in  () at /usr/lib/libSDL2-2.0.so.0
> #6  0x00007f6bde415f9f in  () at /usr/lib/libSDL2-2.0.so.0
> #7  0x00007f6bde4996ea in  () at /usr/lib/libSDL2-2.0.so.0
> #8  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #9  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 7 (Thread 0x7f6bd54eb700 (LWP 2349)):
> #0  0x00007f6c0801ac21 in poll () at /usr/lib/libc.so.6
> #1  0x00007f6c02ef8ee0 in  () at /usr/lib/libglib-2.0.so.0
> #2  0x00007f6c02ef8fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
> #3  0x00007f6c086c6fe4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #4  0x00007f6c086728cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #5  0x00007f6c084bbeb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
> #6  0x00007f6c092ee859 in  () at /usr/lib/libQt5Qml.so.5
> #7  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
> #8  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #9  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 6 (Thread 0x7f6bd5cec700 (LWP 2348)):
> #0  0x00007f6c0742def6 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
> #1  0x00007f6c084c65fd in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
> #2  0x00007f6c084be024 in  () at /usr/lib/libQt5Core.so.5
> #3  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
> #4  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #5  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 5 (Thread 0x7f6bd6f2d700 (LWP 2347)):
> #0  0x00007f6c02ea73a9 in g_mutex_lock () at /usr/lib/libglib-2.0.so.0
> #1  0x00007f6c02ef8ea6 in  () at /usr/lib/libglib-2.0.so.0
> #2  0x00007f6c02ef8fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
> #3  0x00007f6c086c6fe4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #4  0x00007f6c086728cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #5  0x00007f6c084bbeb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
> #6  0x00007f6c092ee859 in  () at /usr/lib/libQt5Qml.so.5
> #7  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
> #8  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #9  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 4 (Thread 0x7f6bebb24700 (LWP 2346)):
> #0  0x00007f6c0801ac21 in poll () at /usr/lib/libc.so.6
> #1  0x00007f6c02ef8ee0 in  () at /usr/lib/libglib-2.0.so.0
> #2  0x00007f6c02ef8fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
> #3  0x00007f6c086c6fe4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #4  0x00007f6c086728cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #5  0x00007f6c084bbeb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
> #6  0x00007f6c09ff3ba6 in  () at /usr/lib/libQt5DBus.so.5
> #7  0x00007f6c084c5f65 in  () at /usr/lib/libQt5Core.so.5
> #8  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #9  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 3 (Thread 0x7f6bf3fff700 (LWP 2345)):
> #0  0x00007f6c0742dafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
> #1  0x00007f6bf8cd91ac in  () at /usr/lib/dri/i965_dri.so
> #2  0x00007f6bf8cd8ee8 in  () at /usr/lib/dri/i965_dri.so
> #3  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #4  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 2 (Thread 0x7f6bfc970700 (LWP 2343)):
> #0  0x00007f6c0742dafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
> #1  0x00007f6c08328cd1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
> #2  0x00007f6c08328cd1 in std::condition_variable::wait(std::unique_lock<std::mutex>&) (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
> #3  0x00007f6c06593f14 in  () at /usr/lib/libQt5WebKit.so.5
> #4  0x00007f6c06594039 in  () at /usr/lib/libQt5WebKit.so.5
> #5  0x00007f6c0832f063 in std::execute_native_thread_routine(void*) (__p=0x560a38301d00) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
> #6  0x00007f6c07427a9d in start_thread () at /usr/lib/libpthread.so.0
> #7  0x00007f6c08025b23 in clone () at /usr/lib/libc.so.6
> 
> Thread 1 (Thread 0x7f6bfc976d80 (LWP 2342)):
> [KCrash Handler]
> #6  0x00007f6c0869ecb8 in QObject::property(char const*) const () at /usr/lib/libQt5Core.so.5
> #7  0x00007f6bf83892d4 in dstyle::Style::drawSlider(QStyleOptionComplex const*, QPainter*, QWidget const*) const () at /usr/lib/qt/plugins/styles/libdstyleplugin.so
> #8  0x00007f6bf8382b29 in dstyle::Style::drawComplexControl(QStyle::ComplexControl, QStyleOptionComplex const*, QPainter*, QWidget const*) const () at /usr/lib/qt/plugins/styles/libdstyleplugin.so
> #9  0x00007f6bda2f2006 in  () at /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
> #10 0x00007f6bda2f2736 in  () at /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
> #11 0x00007f6c096473f3 in QQuickWindowPrivate::polishItems() () at /usr/lib/libQt5Quick.so.5
> #12 0x00007f6c095d4589 in  () at /usr/lib/libQt5Quick.so.5
> #13 0x00007f6c095d5435 in  () at /usr/lib/libQt5Quick.so.5
> #14 0x00007f6c08a28a95 in QWindow::event(QEvent*) () at /usr/lib/libQt5Gui.so.5
> #15 0x00007f6c09651a5c in QQuickWindow::event(QEvent*) () at /usr/lib/libQt5Quick.so.5
> #16 0x00007f6c09a1fe14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #17 0x00007f6c09a276e1 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #18 0x00007f6c08673c39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
> #19 0x00007f6c08a1d3b6 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /usr/lib/libQt5Gui.so.5
> #20 0x00007f6c08a1e0ee in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
> #21 0x00007f6c089f7a3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
> #22 0x00007f6bfba78e1d in  () at /usr/lib/libQt5XcbQpa.so.5
> #23 0x00007f6c086728cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #24 0x00007f6c0867abc6 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
> #25 0x0000560a362602ee in  ()
> #26 0x00007f6c07f4e223 in __libc_start_main () at /usr/lib/libc.so.6
> #27 0x0000560a36260b7e in _start ()
> [Inferior 1 (process 2342) detached]

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
