### ISSUE TITLE
DThemeManager enhancement

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/deepin-tool-kit#18]
Hello, more I think to it, more I think that you should add it or something that looks like it... You should look at my projects:
https://github.com/N1coc4colA/NUI
https://github.com/N1coc4colA/NUI-LIB
https://github.com/N1coc4colA/NUI-TEMPLATE

NUI is the app that provides the service, NUI-LIB is a suit of 3 components and files to use with NUI. There is modified version of DThemeManager, I keeped the same class name to ensure the compatibility: if I use another class with the same namespaces & other in internal (#include "....h") , C++ will take it in first and not your one. So, when your objects call DThemeManager, it will use MY class and not your one. with this, you have a little system of replacement of links and it makes users able to use and set their own theme. I know that there is a work on Chameleon (I think it is to use the same theme as Gtk) but I prefer to say it to you before v20 in case of. You just need to add 4 files and install one app (to modify because I haven't made the .service file for DBus).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
