### ISSUE TITLE
Error: Unable to locate package xcb

### ISSUE THREAD

**Issue by rodobrodo2** [linuxdeepin/deepin-tool-kit#19]
when i try to do :
apt install build-essential git vim xcb libxcb-util0-dev libxcb-ewmh-dev libxcb-randr0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-xinerama0-dev libasound2-dev libxcb-xtest0-dev libxcb-shape0-dev

the errot: unable to locate package xcb apear
i am trying in so diffrent ways to fix it but i can t find nothing , someone can help pls?

**Comment by BLumia** [comment]
Hi,

All repos under the [martyr-deepin](https://github.com/martyr-deepin/) organizations are deprecated. You probably got to the wrong place. If you are looking to build DTK, go to https://github.com/linuxdeepin and search for repos starts with the `dtk` prefix.

**Comment by rodobrodo2** [comment]
i don t know man , i am new at linux , was just following a youtube course and he did this apt install , from various libreries , i had to install xcb packages
