### ISSUE TITLE
Project ERROR: xcb-util development package not found

### ISSUE THREAD

**Issue by xyz1001** [linuxdeepin/deepin-tool-kit#2]
请问在哪可以找到这个包 Project ERROR: xcb-util development package not found

**Comment by cz-guardian** [comment]
@Zix777 Just install the package "libxcb-util-dev" on debian based distros (Ubuntu,Debian,Mint) or xcb-util-devel in RHEL based distros (Fedora,CentOS)

**Comment by zccrs** [comment]
closed

**Comment by ThinkDigitalSoftware** [comment]
`libxcb-util-dev is already the newest version (0.4.0-0ubuntu3).
`Even still I get the error on Ubuntu 17.10 artful

**Comment by nohappiness** [comment]
@ThinkDigitalRepair  You may need to install 'pkg-config' on your system. :smiley:

**Comment by lostinblue** [comment]
I could not find this package in the Debian repositories. I had to get it directly from the freedesktop.org website (developers of the xcb libraries).

**Comment by zccrs** [comment]
@lostinblue 

cat dtkwidget/debian/control|grep xcb-util
sudo apt install PackageName(should be libxcb-util0-dev)
