### ISSUE TITLE
(Wrong) Circular build dependency

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-tool-kit#4]
dde-qt5integration build-depends on libdtkwidget-dev
libdtkwidget-dev depends on libdtkwidget
libdtkwidget depends on dde-qt5integration

AFAIK the third one is not necessary.
Could you please fix it?

**Comment by zccrs** [comment]
This bug has been fixed

**Comment by hosiet** [comment]
Great. Will check it later.
