### ISSUE TITLE
-ldtkbase -ldtkwidget -ldtkutil not found.

### ISSUE THREAD

**Issue by ypingcn** [linuxdeepin/deepin-tool-kit#5]
I want to have a look at dtk so I clone this repo and open ./example/examples.pro in Qt creator.but Qt creator point out that -ldtkbase -ldtkwidget -ldtkutil were not found after compilng. How to deal with it?
My Qt version is 5.8.0,thanks.

**Comment by zhtengw** [comment]
Maybe you should build dtk.pro first.

**Comment by zccrs** [comment]
git clone https://github.com/linuxdeepin/deepin-tool-kit.git
cd deepin-tool-kit
mkdir build && cd build
qmake ..
make
