### ISSUE TITLE
dtksettings development package not found

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/deepin-tool-kit#6]
Project ERROR: dtksettings development package not found
Makefile:108: recipe for target 'sub-dwidget-install_subtargets' failed
make: *** [sub-dwidget-install_subtargets] Error 3

but i have installed 

libdtksettings-0.2 - Deepin Tool Kit Settings library
libdtksettings-0.2-dbgsym - Debug symbols for libdtksettings-0.2
libdtksettings-0.2-dev - Deepin Tool Kit Settings Devel library
libdtksettingsview-0.2 - Deepin Tool Kit Settings UI library
libdtksettingsview-0.2-dbgsym - Debug symbols for libdtksettingsview-0.2
libdtksettingsview-0.2-dev - Deepin Tool Kit Settings UI Devel library

what should i do?

**Comment by zccrs** [comment]
The following packages should be installed: libdtksettings-dev, libdtksettingsview-dev
Not libdtksettings-0.2-dev, libdtksettingsview-0.2-dev

**Comment by PikachuHy** [comment]
ok, thanks
