### ISSUE TITLE
Deepin Tool Kit 重构

### ISSUE THREAD

**Issue by Iceyer** [linuxdeepin/deepin-tool-kit#8]
考虑到DTK的维护以及部分新模块的添加需求，建议对deepin-tool-kit仓库进行如下变更：

1 dtkbase/dtkutil/dtksettings -> 合并进入 dtkcore，建立新仓库 dtkcore。移除dtkcore中和X11/Widget相关的任何代码。
2 dtkweidget/dtksettings 移入新仓库dtkwidget。
3 deepin-tool-kit通过submodule进行管理。
4 新增dtkwm:  处理窗口识别库/xcb功能， 供截图、录屏、系统监视器使用。
5 新增dtkweb: 封装chroium，提高CEF/WebEngine兼容接口。
6 支持Qt Module

大家看看对上面几点有没有看法或者更好的处理。

**Comment by Iceyer** [comment]
dtkwidget TODO:

- [x] DDesktopServices -> dtkwidget
- [x] dsettingsview -> dtkwidget

apps TODO:
- [x] dde-calendar
- [x] dde-control-center
- [x] dde-desktop
- [x] dde-disk-mount-plugin
- [x] dde-dock
- [x] dde-file-manager
- [x] dde-launcher
- [x] dde-polkit-agent
- [x] dde-qt5integration
- [x] dde-session-ui
- [x] dde-trash-plugin
- [x] deepin-appstore
- [x] deepin-boot-maker
- [x] deepin-cloud-scanner
- [x] deepin-deb-installer
- [x] deepin-draw
- [x] deepin-image-viewer
- [x] deepin-license-activator
- [x] deepin-menu
- [x] deepin-music
- [x] deepin-notifications
- [x] deepin-presentation-assistant
- [x] deepin-qml-widgets
- [x] deepin-screen-recorder
- [x] deepin-screenshot
- [x] deepin-shortcut-viewer
- [x] deepin-system-monitor
- [x] deepin-voice-recorder
- [x] printer-driver-deepin-cloud-print

**Comment by Iceyer** [comment]
- [ ] 清理dtkwidget中的x11代码
- [x] 合并dtk-settings-tool
- [x] deepin-tool-kit通过submodule进行管理
- [x] dtkwm: 处理窗口识别库/xcb功能， 供截图、录屏、系统监视器使用。
- [ ] dtkweb: 封装cef
- [x] cmake支持

**Comment by hosiet** [comment]
@Iceyer 对 CEF 的封装稍微有点疑问。之后如果要把相关软件推进 debian 的话 CEF 这种东西应该是很麻烦的，最好能够提供编译时/运行时的替代方案，例如使用 qtwebengine / qtwebkit 而非 CEF。

**Comment by Iceyer** [comment]
@hosiet qtwebkit已经不维护了，不会考虑这个的。
qtwebengine目前的bug太多了，还不是很稳定，可能等稳定一些我们会考虑做一层兼容层。
不过现在deepin官方可能会依赖cef的就deepin-appstore/deepin-manaul, 问题不是很大。其他的都是no-free的第三方应用，不会考虑进debian仓库的。

**Comment by hosiet** [comment]
Qtwebkit 即将有新版放出的，其实可以继续考虑。

**Comment by hosiet** [comment]
http://lists.qt-project.org/pipermail/development/2016-June/026156.html


https://github.com/annulen/webkit

**Comment by Iceyer** [comment]
问题是Qt官方的QtWebkit每个月才一两个提交，其中还有部分是是改版本号。
像wiz笔记等一些应用都已经迁移到webengine了。

**Comment by hosiet** [comment]
我知道这个情况，其实相当于憋大招，合回主线还有些日子，不过快了

**Comment by LinboLen** [comment]
qtwebengine is just shit
